class Config:
    VOICE_RECORDING_MAX_DURATION = 120
    VOICE_RECORDING_SILENCE_DURATION = 2.1
    VOICE_RECORDING_CHUNK_DURATION_MS = 30
    VOICE_RECORDING_VAD_AGGRESSION = 3
    TEXT_MODEL = 'gpt-3.5-turbo'
    AUDIO_MODEL = 'tts-1'
    AUDIO_MODEL_WHISPER = 'whisper-1'
    DEFAULT_INTERVIEW_ROUNDS = 4
    DEFAULT_VOICE = 'shimmer'
    DEFAULT_INPUT_UI = 'voice'
    TEMPORARY_FOLDER = 'tmp'


